"""add_notification_preferences

Revision ID: 976ed5ce6806
Revises: ccbc880f6b5c
Create Date: 2026-04-14 09:06:15.475097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '976ed5ce6806'
down_revision: Union[str, None] = 'ccbc880f6b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_email_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('notification_push_enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_push_enabled')
    op.drop_column('users', 'notification_email_enabled')
    # ### end Alembic commands ###
