"""add notifications models

Revision ID: ccbc880f6b5c
Revises: 0009
Create Date: 2026-04-14 02:21:11.068491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccbc880f6b5c'
down_revision: Union[str, None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('fallback_sent', sa.Boolean(), nullable=False, comment="True if an email was sent because the user didn't read the notification."),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    op.drop_constraint(op.f('documents_owner_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('onboarding_profiles_user_id_fkey'), 'onboarding_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'onboarding_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('uq_payments_yookassa_id'), 'payments', type_='unique')
    op.drop_constraint(op.f('projects_user_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('projects', 'status')
    op.drop_constraint(op.f('simulation_sessions_user_id_fkey'), 'simulation_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'simulation_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('speech_drafts_user_id_fkey'), 'speech_drafts', type_='foreignkey')
    op.create_foreign_key(None, 'speech_drafts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('uq_subscriptions_user_id'), 'subscriptions', type_='unique')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.drop_constraint(op.f('uq_usage_counters_user_id'), 'usage_counters', type_='unique')
    op.drop_index(op.f('ix_usage_counters_user_id'), table_name='usage_counters')
    op.create_index(op.f('ix_usage_counters_user_id'), 'usage_counters', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_counters_user_id'), table_name='usage_counters')
    op.create_index(op.f('ix_usage_counters_user_id'), 'usage_counters', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_usage_counters_user_id'), 'usage_counters', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_subscriptions_user_id'), 'subscriptions', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'speech_drafts', type_='foreignkey')
    op.create_foreign_key(op.f('speech_drafts_user_id_fkey'), 'speech_drafts', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'simulation_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('simulation_sessions_user_id_fkey'), 'simulation_sessions', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('projects', sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_user_id_fkey'), 'projects', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_payments_yookassa_id'), 'payments', ['yookassa_payment_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'onboarding_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('onboarding_profiles_user_id_fkey'), 'onboarding_profiles', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_owner_id_fkey'), 'documents', 'users', ['owner_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
